# Generated by Django 4.2.7 on 2023-11-21 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('spas', '0001_initial'),
        ('services', '0002_alter_service_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.category'),
        ),
        migrations.AddField(
            model_name='service',
            name='spa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='spas.spa'),
        ),
    ]
