# Generated by Django 4.2.7 on 2023-11-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('personal_spa', 'Personal SPA'), ('client', 'Client')], default='client', max_length=50),
        ),
    ]
